# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a219e2df759eaa417f60eec1c0df01e06053afe56ff44fbf74c14d2d7e0eba0ef038c5ee6073884307d39fbc8aa7b117904f83dc75d1a6d743af162e10156ed

test:
  secret_key_base: 5224affdcc30799f51cbcd81647287c02d532f2b4c42560b03fd51b19934318c1e2cfc6ec7df7d069132db8991e1d82ffd860b3420bf9884efe8a636098f8409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
